//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Swigged.Cuda {

public enum CUipcMem_flags {
  CU_IPC_MEM_LAZY_ENABLE_PEER_ACCESS = 0x1
}

}
